import type { User, Asset, Ticket, AuditLog } from './types';

export const mockUsers: User[] = [
  { id: 'user-1', name: 'Əli Vəliyev', email: 'ali.v@example.com', role: 'Super Admin', region: 'Bütün', avatar: '/avatars/01.png' },
  { id: 'user-2', name: 'Sara Qasımlı', email: 'sara.q@example.com', role: 'Admin', region: 'Bakı', avatar: '/avatars/02.png' },
  { id: 'user-3', name: 'Tural Məmmədov', email: 'tural.m@example.com', role: 'Səhra istifadəçisi', region: 'Bakı', avatar: '/avatars/03.png' },
  { id: 'user-4', name: 'Leyla Hüseynova', email: 'leyla.h@example.com', role: 'Səhra istifadəçisi', region: 'Gəncə', avatar: '/avatars/04.png' },
  { id: 'user-5', name: 'Fərid İsmayılov', email: 'farid.i@example.com', role: 'Səhra istifadəçisi', region: 'Sumqayıt', avatar: '/avatars/05.png' },
];

export const mockAssets: Asset[] = [
  { 
    id: 'asset-1', 
    name: 'Nizami küç. dirək 1', 
    type: 'Dirək', 
    region: 'Bakı', 
    location: { lat: 40.3792, lng: 49.8492 }, 
    status: 'Aktiv', 
    addedBy: 'user-3', 
    addedDate: '2023-10-01',
    istehsalci: 'İDEA',
    hundurluk: 4,
    reng: 'Boz',
    nov: 'T',
    hendesiForma: 'Kvadrat',
    material: 'Qara metal',
    qurasdirilmaTarixi: '2020-dən əvvəl',
    istismarVeziyyeti: 'Yararlı',
    qol: 'Yararlı',
    etek: 'Yararlı',
    sapka: 'Yararlı',
    qapaq: 'Yararlı',
    direyinTemizliyi: 'Təmiz',
    torpaqlanma: 'Var',
    bunovreNovu: 'Stasionar',
    bunovreVeziyyeti: 'Yararlı',
    ankerVeziyyeti: 'Yararlı'
  },
  { 
    id: 'asset-2', 
    name: '28 May qovşaq qutusu', 
    type: 'Qutu', 
    region: 'Bakı', 
    location: { lat: 40.3798, lng: 49.8499 }, 
    status: 'Aktiv', 
    addedBy: 'user-3', 
    addedDate: '2023-10-02', 
    qurasdirilmaTarixi: '2020-dən əvvəl',
    istehsalci: 'İDEA',
    tipi: 'Yer',
    soyutmaSistemi: 'Yoxdur',
    termalSensor: 'Var',
    reng: 'Boz',
    acarYeri: 'Plastik',
    refSayi: 'Rəfsiz',
    berkidilmeUsulu: 'Kələpçə',
    torpaqlanma: 'Var',
    etiket: 'Var',
    istismarVeziyyeti: 'Yararlı',
    elaveKilidMexanizmi: 'Var',
    kilidIstismarVeziyyeti: 'Yararlı',
    qutununXariciTemizliyi: 'Təmiz',
    qutununDaxiliTemizliyi: 'Təmiz',
  },
  { 
    id: 'asset-3', 
    name: 'İçərişəhər Cam 01', 
    type: 'Kamera', 
    region: 'Bakı', 
    location: { lat: 40.3582, lng: 49.8336 }, 
    status: 'Təmir', 
    addedBy: 'user-2', 
    addedDate: '2023-09-15', 
    qurasdirilmaTarixi: '2022-05-20',
    marka: 'Hikvision',
    model: 'Dahua DH-SD8A3440GA-HNV',
    funksiya: 'PTZ müşahidə',
    kameraNovu: 'Daxili',
    adapter: 'Dom kamera Tandem VU adapter CUV-090S036SP',
    reng: 'Ağ',
    kameraQolu: 'Var',
    qolIstismarVeziyyeti: 'Yararlı',
    montajAksesuari: 'Təkli',
    montajAksesuariIstismarVeziyyeti: 'Yararlı',
    kameraTemizliyi: 'Təmiz',
  },
  { 
    id: 'asset-4', 
    name: 'Gəncə dirək 1', 
    type: 'Dirək', 
    region: 'Gəncə', 
    location: { lat: 40.6828, lng: 46.3606 }, 
    status: 'Aktiv', 
    addedBy: 'user-4', 
    addedDate: '2023-11-05',
    istehsalci: 'OZON',
    hundurluk: 5,
    reng: 'Qara',
    nov: 'I',
    hendesiForma: 'Dairəvi',
    material: 'Qalvanizasiya olunmuş qara metal',
    qurasdirilmaTarixi: '2023',
    istismarVeziyyeti: 'Yararsız',
    qol: 'Yararsız',
    etek: 'Yararsız',
    sapka: 'Yararsız',
    qapaq: 'Yararsız',
    direyinTemizliyi: 'Çirkli',
    torpaqlanma: 'Yoxdur',
    bunovreNovu: 'Səyyar bastırılmış',
    bunovreVeziyyeti: 'Aşınmış',
    ankerVeziyyeti: 'Yararsız'
  },
  { id: 'asset-5', name: 'Bulvar Park Router', type: 'Router', region: 'Sumqayıt', location: { lat: 40.5897, lng: 49.6686 }, status: 'Qeyri-aktiv', addedBy: 'user-5', addedDate: '2023-08-20', qurasdirilmaTarixi: '2021-11-11' },
  { 
    id: 'asset-6', 
    name: 'Fəvvarələr Meydanı Cam 05', 
    type: 'Kamera', 
    region: 'Bakı', 
    location: { lat: 40.3703, lng: 49.8344 }, 
    status: 'Aktiv', 
    addedBy: 'user-3', 
    addedDate: '2023-11-10', 
    qurasdirilmaTarixi: '2023-03-01',
    marka: 'AXİS',
    model: 'Dom kamera Tandem VU Hikvision DS-2SF8C442MXG-ElW/26 FO',
    funksiya: 'PTZ üz tanıma',
    adapter: 'Dom  Adapter Hikvision TEAC-66-243000V, AC230V,AC24VA3A',
    kameraNovu: 'Xarici',
    reng: 'Boz',
    kameraQolu: 'Yox',
    qolIstismarVeziyyeti: 'Yararsız',
    montajAksesuari: 'Üçlü',
    montajAksesuariIstismarVeziyyeti: 'Yararsız',
    kameraTemizliyi: 'Çirkli',
  },
  {
    id: 'asset-7',
    name: 'Nizami küç. Data Kabeli',
    type: 'Data Kabeli',
    region: 'Bakı',
    location: { lat: 40.3792, lng: 49.8492 },
    status: 'Aktiv',
    addedBy: 'user-3',
    addedDate: '2023-10-01',
    ethernetTipi: 'CAT6 Kabel Outdoor (Black)',
    ethernetUzunluq: 150,
    patchcordTipi: 'FO Patchcord 7m',
    patchcordUzunluq: 7,
    optikYerlesme: 'Yuxarıda',
  },
  {
    id: 'asset-8',
    name: 'Nizami küç. Elektrik Kabeli',
    type: 'Elektrik Kabeli',
    region: 'Bakı',
    location: { lat: 40.3792, lng: 49.8492 },
    status: 'Aktiv',
    addedBy: 'user-3',
    addedDate: '2023-10-01',
    kabelTipi: 'Elektrik kabeli 2x2.25',
    kabelUzunluq: 100,
    uzaticiYuvaSayi: 4,
    uzaticiUzunluq: 2,
    birlesmeUsulu: 'Birbaşa'
  },
  {
    id: 'asset-9',
    name: 'Mərkəzi Bank Switch',
    type: 'Switch',
    region: 'Bakı',
    location: { lat: 40.3713, lng: 49.8465 },
    status: 'Aktiv',
    addedBy: 'user-2',
    addedDate: '2023-07-15',
    marka: 'Huawei',
    model: 'S5735-L8P4X-QA-V2 (8x10/100/1000BASE-T)',
    adapter: 'Cisco Power Adapter PWR-IE 170W-PC-AC',
    qurasdirilmaTarixi: '2023-07-10',
    switchTipi: 'İndustrial tipli',
    management: 'idarə olunan',
    switchYeri: 'Qapı',
    konfiqurasiya: 'olunub',
    sfpModul: 'Allied Telesis 1310/1490',
    ups: 'Makelsan',
    stabilizator: 'Tuncmatik',
  },
  {
    id: 'asset-10',
    name: 'Fransız Dirək',
    type: 'Dirək',
    region: 'Bakı',
    location: { lat: 40.38, lng: 49.85 },
    status: 'Aktiv',
    addedBy: 'user-2',
    addedDate: '2023-11-25',
    istehsalci: 'FRANSIZ',
    hundurluk: 6,
    reng: 'Ağ',
    nov: 'Г',
    hendesiForma: 'Dairəvi Xonçalı',
    material: 'Aluminium',
    qurasdirilmaTarixi: '2021',
    istismarVeziyyeti: 'Restovrasiya olunmalıdır',
    qol: 'Restovrasiya olunmalıdır',
    etek: 'Restovrasiya olunmalıdır',
    sapka: 'Restovrasiya olunmalıdır',
    qapaq: 'Restovrasiya olunmalıdır',
    direyinTemizliyi: 'Təmiz',
    torpaqlanma: 'Var',
    bunovreNovu: 'Səyyar yer üstü',
    bunovreVeziyyeti: 'Ölçü qüsurlu',
    ankerVeziyyeti: 'Yararlı',
  }
];

export const mockTickets: Ticket[] = [
  { id: 'ticket-1', assetId: 'asset-3', issue: 'Kamera oflayndır', status: 'İcra olunur', assignedTo: 'user-3', createdDate: '2023-11-20' },
  { id: 'ticket-2', assetId: 'asset-5', issue: 'Router IP vermir', status: 'Açıq', createdDate: '2023-11-21' },
  { id: 'ticket-3', assetId: 'asset-1', issue: 'Dirəkdə elektrik kəsintisi', status: 'Bağlı', assignedTo: 'user-3', createdDate: '2023-11-18' },
  { id: 'ticket-4', assetId: 'asset-4', issue: 'Dirək aşınmaya məruz qalıb', status: 'Açıq', assignedTo: 'user-4', createdDate: '2023-11-22' },
];

export const mockAuditLogs: AuditLog[] = [
  { id: 'log-1', userId: 'user-1', action: 'İstifadəçi Yaradıldı', timestamp: '2023-11-22T09:05:12Z', details: 'Fərid İsmayılov (user-5) adlı istifadəçi yaradıldı' },
  { id: 'log-2', userId: 'user-3', action: 'Asset Əlavə Edildi', timestamp: '2023-11-22T09:01:45Z', details: 'Fəvvarələr Meydanı Cam 05 (asset-6) əlavə edildi' },
  { id: 'log-3', userId: 'user-2', action: 'Tiket Təyin Edildi', timestamp: '2023-11-22T08:55:30Z', details: 'Tiket-1 Tural Məmmədova təyin edildi' },
  { id: 'log-4', userId: 'user-4', action: 'Asset Statusu Dəyişdirildi', timestamp: '2023-11-21T15:30:00Z', details: 'Asset-4-ün statusu Aktiv olaraq dəyişdirildi' },
  { id: 'log-5', userId: 'user-1', action: 'İstifadəçi Girişi', timestamp: '2023-11-21T15:25:10Z', details: 'Əli Vəliyev daxil oldu' },
];
